name: Java CI with Maven (Subfolder)

on:
  push:
    branches: [ "main" ]
    paths:
      - '15-10-2025/Oct15-SB-Jenkins/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '15-10-2025/Oct15-SB-Jenkins/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 15-10-2025/Oct15-SB-Jenkins

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
        with:
          directory: 15-10-2025/Oct15-SB-Jenkins
